#!/bin/sh

RUNFILE="/usr/share/daed-runfiles/25-luci-app-dead_1.28-aarch64_cortex-a53.run"
WORKDIR="/tmp/daed-runfiles"

[ -x /sbin/apk ] || [ -x /usr/bin/apk ] || exit 0
[ -s "$RUNFILE" ] || exit 0
[ -x /usr/bin/daed ] && exit 0

rm -rf "$WORKDIR"
mkdir -p "$WORKDIR" || exit 1

sh "$RUNFILE" --target "$WORKDIR" --noexec || {
    rm -rf "$WORKDIR"
    exit 1
}

apk add --allow-untrusted "$WORKDIR"/*.apk || {
    rm -rf "$WORKDIR"
    exit 1
}

rm -rf "$WORKDIR"
exit 0
